In [28]:
import pandas as pd

In [29]:
df = pd.read_csv("/content/amazon_grocery.csv", low_memory=False)

In [30]:
df.columns

Index(['name', 'price', 'url', 'keyword', 'Brand Name', 'Flavor',
       'Allergen Information', 'Item Weight', 'Item Form', 'Unit Count',
       ...
       'Sheet Count', 'Package Type', 'Manufacturer Food Processing Method',
       'Fastener Type', 'Metal Type', 'Thread Type', 'Inside Thread Size',
       'Genre', 'Edition', 'Are batteries required?'],
      dtype='object', length=101)

In [31]:
df.head()

,name,price,url,keyword,Brand Name,Flavor,Allergen Information,Item Weight,Item Form,Unit Count,...,Sheet Count,Package Type,Manufacturer Food Processing Method,Fastener Type,Metal Type,Thread Type,Inside Thread Size,Genre,Edition,Are batteries required?
0,Juhayna,257,https://www.amazon.eg/-/en/JUHAYNA-Carton-Crea...,milk,Juhayna,Full Cream,Dairy,1 Kilograms,Liquid,1 Liters,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Almarai,49,https://www.amazon.eg/-/en/Almarai-plain-milk-...,milk,Almarai,Without Flavor,Milk,1 Kilograms,Liquid,1000 Milliliters,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Juhayna,515,https://www.amazon.eg/-/en/JUHAYNA-Carton-Crea...,milk,Juhayna,Full Cream,Dairy,2 Kilograms,Liquid,2 Liters,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Almarai,302,https://www.amazon.eg/-/en/Almarai-Milk-Full-F...,milk,Almarai,coffee,Milk,1 Kilograms,Liquid,1 Liters,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Almarai,49,https://www.amazon.eg/-/en/Almarai-Plain-Full-...,milk,Almarai,unflavored,Milk,1 Kilograms,Liquid,1000 Count,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
cols = ['name', 'price', 'keyword', 'Brand Name', 'Flavor',
        'Allergen Information', 'Item Weight', 'Item Form', 'Unit Count']
df = df[cols]

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9405 entries, 0 to 9404
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   name                  9405 non-null   object
 1   price                 9026 non-null   object
 2   keyword               9405 non-null   object
 3   Brand Name            9096 non-null   object
 4   Flavor                5750 non-null   object
 5   Allergen Information  1016 non-null   object
 6   Item Weight           5498 non-null   object
 7   Item Form             5174 non-null   object
 8   Unit Count            4145 non-null   object
dtypes: object(9)
memory usage: 661.4+ KB

In [36]:
print(df.head())

      name price keyword Brand Name          Flavor Allergen Information  \
0  Juhayna   257    milk    Juhayna      Full Cream                Dairy
1  Almarai    49    milk    Almarai  Without Flavor                 Milk
2  Juhayna   515    milk    Juhayna      Full Cream                Dairy
3  Almarai   302    milk    Almarai          coffee                 Milk
4  Almarai    49    milk    Almarai      unflavored                 Milk

   Item Weight Item Form        Unit Count
0  1 Kilograms    Liquid          1 Liters
1  1 Kilograms    Liquid  1000 Milliliters
2  2 Kilograms    Liquid          2 Liters
3  1 Kilograms    Liquid          1 Liters
4  1 Kilograms    Liquid        1000 Count

**my target is to determine the price so Allergen feature is not important**

In [37]:
df = df.drop(columns=['Allergen Information'])

In [38]:
df.columns

Index(['name', 'price', 'keyword', 'Brand Name', 'Flavor', 'Item Weight',
       'Item Form', 'Unit Count'],
      dtype='object')

**preprocess data..It includes three phase:
1.firstly:Clean text data**

In [39]:
text_cols = ['name','keyword','Brand Name','Flavor','Item Form']

for col in text_cols:
    df[col] = df[col].astype(str).str.strip().str.lower()

**Clean numerical features**

In [41]:
df['price'] = pd.to_numeric(df['price'], errors='coerce')
df = df.dropna(subset=['price'])

In [42]:
df['price']

0       257.0
1        49.0
2       515.0
3       302.0
4        49.0
        ...
9399    299.0
9400    244.0
9401    404.0
9402    250.0
9404    220.0
Name: price, Length: 8627, dtype: float64

**ItemWeight cleaning**

In [43]:
def convert_weight(x):
    x = str(x).lower()

    if 'kilogram' in x:
        return float(x.split()[0])

    elif 'gram' in x:
        return float(x.split()[0]) / 1000

    elif 'liter' in x:
        return float(x.split()[0])

    elif 'milliliter' in x:
        return float(x.split()[0]) / 1000

    else:
        return None

df['Item Weight'] = df['Item Weight'].apply(convert_weight)

**Clean the UnitCount Feature**

In [44]:
df['Unit Count'] = pd.to_numeric(df['Unit Count'], errors='coerce')

In [45]:
X = df.drop('price', axis=1)   # features
y = df['price']                # target

In [46]:
print(X.head())

      name keyword Brand Name          Flavor  Item Weight Item Form  \
0  juhayna    milk    juhayna      full cream          1.0    liquid
1  almarai    milk    almarai  without flavor          1.0    liquid
2  juhayna    milk    juhayna      full cream          2.0    liquid
3  almarai    milk    almarai          coffee          1.0    liquid
4  almarai    milk    almarai      unflavored          1.0    liquid

   Unit Count
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN

In [47]:
print(y.head())

0    257.0
1     49.0
2    515.0
3    302.0
4     49.0
Name: price, dtype: float64

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8627 entries, 0 to 9404
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         8627 non-null   object
 1   price        8627 non-null   float64
 2   keyword      8627 non-null   object
 3   Brand Name   8627 non-null   object
 4   Flavor       8627 non-null   object
 5   Item Weight  5050 non-null   float64
 6   Item Form    8627 non-null   object
 7   Unit Count   0 non-null      float64
dtypes: float64(3), object(5)
memory usage: 606.6+ KB

In [50]:
df = df.drop(columns=['Unit Count'])

In [51]:
df.shape

(8627, 7)

In [52]:
df.columns

Index(['name', 'price', 'keyword', 'Brand Name', 'Flavor', 'Item Weight',
       'Item Form'],
      dtype='object')

**To Imput Itemweight values**

In [53]:
df['Item Weight'] = df['Item Weight'].fillna(df['Item Weight'].median())

In [54]:
df['Item Weight']

0       1.000
1       1.000
2       2.000
3       1.000
4       1.000
        ...
9399    0.454
9400    0.125
9401    0.400
9402    0.200
9404    0.340
Name: Item Weight, Length: 8627, dtype: float64

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8627 entries, 0 to 9404
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         8627 non-null   object
 1   price        8627 non-null   float64
 2   keyword      8627 non-null   object
 3   Brand Name   8627 non-null   object
 4   Flavor       8627 non-null   object
 5   Item Weight  8627 non-null   float64
 6   Item Form    8627 non-null   object
dtypes: float64(2), object(5)
memory usage: 539.2+ KB

In [57]:
df.shape

(8627, 7)

**Done....Step2 Our model do not recognize text using TF_IDF for nameofproduct**

In [58]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=500)

name_features = tfidf.fit_transform(df['name'])

**OneHot encoding for other textual features**

In [59]:
from sklearn.preprocessing import OneHotEncoder

cat_cols = ['keyword','Brand Name','Flavor','Item Form']

encoder = OneHotEncoder()

cat_features = encoder.fit_transform(df[cat_cols])

**numerical features....So,we distribute it into text features>>Tf_IDF...cat features>>one hot...numerical features**

In [60]:
num_features = df[['Item Weight']]

**Combine all features**

In [61]:
from scipy.sparse import hstack

X = hstack([name_features, cat_features, num_features])

**Just for test on Linear Regression**

In [62]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X, y)

LinearRegression()

In [66]:
from scipy.sparse import hstack

X = hstack([name_features, cat_features, num_features])

X = X.tocsr()

model.fit(X, y)

model.predict(X[:5])

array([386.59618052, 198.97367896, 386.554708  , 160.61761033,
       202.53263678])

In [65]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_num_scaled = scaler.fit_transform(df[['Item Weight']])

In [67]:
from sklearn.model_selection import train_test_split
y = df['price']

X_train, X_test, y_train, y_test = train_test_split(X_num_scaled, y, test_size=0.2, random_state=42)

In [70]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import OneHotEncoder
from scipy.sparse import hstack
tfidf = TfidfVectorizer(max_features=500)
X_name = tfidf.fit_transform(df['name'])

cat_cols = ['keyword','Brand Name','Flavor','Item Form']
encoder = OneHotEncoder()
X_cat = encoder.fit_transform(df[cat_cols])

import numpy as np
X_num_dense = np.array(X_num_scaled)

from scipy.sparse import csr_matrix
X_num_sparse = csr_matrix(X_num_dense)

X_final = hstack([X_name, X_cat, X_num_sparse]).tocsr()

In [71]:
X_train, X_test, y_train, y_test = train_test_split(
    X_final, y, test_size=0.2, random_state=42
)

**Ready To be pushed to DeepLearning Model**